import React from 'react';
import { 
  Printer, 
  Download, 
  ArrowLeft, 
  ShieldCheck, 
  QrCode, 
  CheckCircle, 
  Award, 
  Calendar, 
  MapPin, 
  User, 
  Scale, 
  Sparkles,
  Info,
  Layers
} from 'lucide-react';
import { AssessmentRecord, Language, ViewMode } from '../types';
import { translations } from '../utils/translations';

interface DigitalReportProps {
  record: AssessmentRecord;
  onBackToDashboard: () => void;
  language: Language;
}

export const DigitalReport: React.FC<DigitalReportProps> = ({
  record,
  onBackToDashboard,
  language,
}) => {
  const t = translations[language];

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const reportData = {
      title: "ONION QUALITY ASSESSMENT REPORT",
      disclaimer: "This report is generated by an SIH prototype operating in Demo Mode. It is not an official quality certificate.",
      reportId: record.reportId,
      batchId: record.batch.batchId,
      procurementCentre: record.batch.procurementCentre,
      inspector: record.batch.inspectorName,
      dateTime: record.timestamp,
      onionVariety: record.batch.onionVariety,
      approxQuantity: record.batch.approxQuantity,
      aiDemoAnalysis: {
        totalAnalyzed: record.totalAnalyzed,
        counts: record.counts,
        percentages: record.percentages,
      },
      demonstrationGrading: {
        gradeA: `${record.gradeA}%`,
        gradeURS: `${record.gradeURS}%`,
      },
      assessmentSummary: record.qualitySummary,
      generatedAt: new Date().toISOString(),
      sihProblemStatement: "SIH26031"
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `OnionQualityReport_${record.batch.batchId}_${record.reportId}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-20">
      {/* Action buttons (hidden during print) */}
      <div className="no-print flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 bg-white p-4 rounded-2xl border border-[#cfcbb8] shadow-xs">
        <button
          onClick={onBackToDashboard}
          className="inline-flex items-center justify-center gap-1.5 text-xs font-bold text-[#1c2a20] hover:bg-[#f1f6f0] bg-white border border-[#cfcbb8] px-4 py-2.5 rounded-xl transition cursor-pointer shadow-2xs"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>{t.backToDashboard}</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownload}
            className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-1.5 text-xs font-bold text-[#1c2a20] bg-white hover:bg-[#f1f6f0] border border-[#cfcbb8] px-4 py-2.5 rounded-xl transition shadow-2xs cursor-pointer"
            title="Download full JSON audit record"
          >
            <Download className="w-4 h-4 text-[#55665b]" />
            <span>{t.downloadReport}</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-1.5 text-xs font-bold text-white bg-[#1c5a35] hover:bg-[#174327] px-5 py-2.5 rounded-xl transition shadow-md cursor-pointer active:scale-95"
            title="Print or Save as PDF"
          >
            <Printer className="w-4 h-4" />
            <span>{t.printReport}</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document */}
      <div className="printable-card bg-white rounded-3xl border-2 border-[#cfcbb8] shadow-sm p-6 sm:p-10 space-y-8 relative overflow-hidden">
        {/* Subtle Watermark Stamp */}
        <div className="absolute right-6 top-24 pointer-events-none opacity-10 select-none rotate-12 border-4 border-[#174327] rounded-3xl p-4 text-[#174327] text-center font-black tracking-widest text-xs uppercase font-heading">
          SIH 2026 PROTOTYPE<br />
          DEMO INSPECTION<br />
          LOCAL TEST ONLY
        </div>

        {/* Official Header */}
        <div className="border-b-2 border-[#1c2a20] pb-6 space-y-4">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-2xl bg-[#174327] border border-[#0e2f1c] flex items-center justify-center text-[#f2c14e] shadow-md font-heading font-extrabold text-xl">
                OG
              </div>
              <div>
                <div className="text-[11px] font-bold text-[#55665b] tracking-wider uppercase font-heading">
                  {t.officialDemoHeader}
                </div>
                <h1 className="text-xl sm:text-2xl font-black text-[#174327] tracking-tight font-heading">
                  {t.reportTitle}
                </h1>
                <p className="text-xs text-[#1c5a35] font-bold">
                  Problem Statement SIH26031 • Objective Quality Assurance
                </p>
              </div>
            </div>

            {/* QR Code Verification Simulation */}
            <div className="hidden sm:flex flex-col items-center text-center p-2.5 bg-[#f7f5ee] rounded-2xl border border-[#cfcbb8] text-[10px] text-[#55665b]">
              <svg className="w-16 h-16 text-[#1c2a20]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                <rect x="3" y="3" width="7" height="7" rx="1" fill="#1c2a20"/>
                <rect x="14" y="3" width="7" height="7" rx="1" fill="#1c2a20"/>
                <rect x="3" y="14" width="7" height="7" rx="1" fill="#1c2a20"/>
                <path d="M14 14h2v2h-2z M18 14h3v3h-3z M14 18h3v3h-3z M19 19h2v2h-2z" fill="#1c2a20" />
              </svg>
              <span className="font-mono mt-1 text-[9px] font-bold">{record.reportId}</span>
            </div>
          </div>

          {/* Report Metadata Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 text-xs">
            <div className="space-y-0.5">
              <span className="text-[#55665b] font-semibold uppercase text-[10px] block">{t.reportId}</span>
              <span className="font-mono font-bold text-[#1c2a20] text-xs sm:text-sm">{record.reportId}</span>
            </div>
            <div className="space-y-0.5">
              <span className="text-[#55665b] font-semibold uppercase text-[10px] block">{t.batchId}</span>
              <span className="font-mono font-bold text-[#1c2a20] text-xs sm:text-sm">{record.batch.batchId}</span>
            </div>
            <div className="space-y-0.5">
              <span className="text-[#55665b] font-semibold uppercase text-[10px] block">{t.dateTime}</span>
              <span className="font-bold text-[#1c2a20]">{record.batch.date}</span>
            </div>
            <div className="space-y-0.5">
              <span className="text-[#55665b] font-semibold uppercase text-[10px] block">{t.onionVariety}</span>
              <span className="font-bold text-[#1c2a20] font-heading">{record.batch.onionVariety}</span>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2 text-xs border-t border-[#f1f6f0]">
            <div>
              <span className="text-[#55665b] font-semibold uppercase text-[10px] block">{t.procurementCentreLabel}</span>
              <span className="font-bold text-[#1c2a20]">{record.batch.procurementCentre}</span>
            </div>
            <div>
              <span className="text-[#55665b] font-semibold uppercase text-[10px] block">{t.inspectorName}</span>
              <span className="font-bold text-[#1c2a20]">{record.batch.inspectorName} (Officer ID: INSP-2026)</span>
            </div>
          </div>
        </div>

        {/* SECTION 1: QUALITY ANALYSIS */}
        <div className="space-y-4">
          <div className="flex items-center justify-between border-b border-[#e4e1d3] pb-2">
            <h2 className="text-sm font-black text-[#174327] uppercase tracking-wider font-heading flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-[#8a5f12]" />
              <span>{record.isRealScan ? "COMPUTER VISION QUALITY INSPECTION" : "AI DEMO ANALYSIS"}</span>
            </h2>
            <span className="text-xs font-bold text-[#55665b]">
              {t.totalOnionsAnalyzed}: <span className="font-mono font-black text-[#1c2a20]">{record.totalAnalyzed}</span>
            </span>
          </div>

          {/* Defect Percentages Table */}
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="bg-[#f7f5ee] text-[#55665b] font-bold uppercase tracking-wider text-[10px] border-b border-[#cfcbb8]">
                  <th className="py-2.5 px-3 rounded-l-lg">Defect Classification</th>
                  <th className="py-2.5 px-3">Visual Markers & Symptoms</th>
                  <th className="py-2.5 px-3 text-right">Bulb Count</th>
                  <th className="py-2.5 px-3 text-right rounded-r-lg">Calculated %</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#f1f6f0]">
                <tr>
                  <td className="py-3 px-3 font-bold text-[#1c5a35] flex items-center gap-1.5 font-heading">
                    <span className="w-2 h-2 rounded-full bg-[#10b981]" />
                    {t.healthy}
                  </td>
                  <td className="py-3 px-3 text-[#55665b]">Intact dry skins, sound neck, no rot or sprouting</td>
                  <td className="py-3 px-3 text-right font-mono font-bold text-[#1c2a20]">{record.counts.healthy}</td>
                  <td className="py-3 px-3 text-right font-mono font-black text-[#1c5a35]">{record.percentages.healthy}%</td>
                </tr>
                <tr>
                  <td className="py-3 px-3 font-bold text-[#8a5f12] flex items-center gap-1.5 font-heading">
                    <span className="w-2 h-2 rounded-full bg-[#f59e0b]" />
                    {t.damaged}
                  </td>
                  <td className="py-3 px-3 text-[#55665b]">Surface mechanical damage, bruising, deep peelings</td>
                  <td className="py-3 px-3 text-right font-mono font-bold text-[#1c2a20]">{record.counts.damaged}</td>
                  <td className="py-3 px-3 text-right font-mono font-black text-[#8a5f12]">{record.percentages.damaged}%</td>
                </tr>
                <tr>
                  <td className="py-3 px-3 font-bold text-[#a93b2e] flex items-center gap-1.5 font-heading">
                    <span className="w-2 h-2 rounded-full bg-[#a93b2e]" />
                    {t.rotten}
                  </td>
                  <td className="py-3 px-3 text-[#55665b]">Bacterial soft rot, black mold spores, basal decay</td>
                  <td className="py-3 px-3 text-right font-mono font-bold text-[#1c2a20]">{record.counts.rotten}</td>
                  <td className="py-3 px-3 text-right font-mono font-black text-[#a93b2e]">{record.percentages.rotten}%</td>
                </tr>
                <tr>
                  <td className="py-3 px-3 font-bold text-[#7e22ce] flex items-center gap-1.5 font-heading">
                    <span className="w-2 h-2 rounded-full bg-[#9333ea]" />
                    {t.sprouted}
                  </td>
                  <td className="py-3 px-3 text-[#55665b]">Emergent green shoots &gt; 5mm protruding from neck apex</td>
                  <td className="py-3 px-3 text-right font-mono font-bold text-[#1c2a20]">{record.counts.sprouted}</td>
                  <td className="py-3 px-3 text-right font-mono font-black text-[#7e22ce]">{record.percentages.sprouted}%</td>
                </tr>
                <tr>
                  <td className="py-3 px-3 font-bold text-[#0e7490] flex items-center gap-1.5 font-heading">
                    <span className="w-2 h-2 rounded-full bg-[#0891b2]" />
                    {t.undersized}
                  </td>
                  <td className="py-3 px-3 text-[#55665b]">Bulb diameter calibrated below 40mm standard grade (requires reference scale)</td>
                  <td className="py-3 px-3 text-right font-mono font-bold text-[#1c2a20]">{record.counts.undersized}</td>
                  <td className="py-3 px-3 text-right font-mono font-black text-[#0e7490]">{record.percentages.undersized}%</td>
                </tr>
                {record.counts.unableToDetermine > 0 && (
                  <tr className="bg-[#f8fafc]">
                    <td className="py-3 px-3 font-bold text-[#475569] flex items-center gap-1.5 font-heading">
                      <span className="w-2 h-2 rounded-full bg-[#64748b]" />
                      Unable to determine
                    </td>
                    <td className="py-3 px-3 text-[#64748b] italic">Image unclear, low contrast, or non-bulb profile (never counted as healthy)</td>
                    <td className="py-3 px-3 text-right font-mono font-bold text-[#475569]">{record.counts.unableToDetermine}</td>
                    <td className="py-3 px-3 text-right font-mono font-black text-[#475569]">{record.percentages.unableToDetermine || 0}%</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Individual Image Breakdown in Digital Report */}
          {record.imageItems && record.imageItems.length > 0 && (
            <div className="pt-4 border-t border-[#e4e1d3] space-y-3">
              <h3 className="text-xs font-bold text-[#174327] uppercase tracking-wider font-heading">
                Individual Photographic Specimen Audit ({record.imageItems.length} Images Analyzed)
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                {record.imageItems.map((item) => (
                  <div key={item.id} className="p-2.5 rounded-xl border border-[#cfcbb8] bg-[#f7f5ee] flex items-start gap-2.5 text-xs">
                    <img
                      src={item.imageSrc}
                      alt={`Item ${item.imageIndex}`}
                      className="w-12 h-12 rounded-lg object-contain bg-[#0b2013] border border-[#cfcbb8] shrink-0"
                    />
                    <div className="space-y-0.5 min-w-0">
                      <div className="flex items-center justify-between gap-1">
                        <span className="font-bold text-[#1c2a20] truncate">Image {item.imageIndex}</span>
                        <span className="text-[10px] font-bold uppercase font-mono px-1.5 py-0.2 rounded bg-white border border-[#cfcbb8]">
                          {item.label}
                        </span>
                      </div>
                      <p className="text-[10px] text-[#55665b] line-clamp-2">{item.reason}</p>
                      {item.confidence !== undefined && (
                        <span className="text-[9px] font-mono text-[#174327] font-bold block">
                          Confidence: {item.confidence}%
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* SECTION 2: DEMONSTRATION GRADING */}
        <div className="space-y-4">
          <div className="flex items-center justify-between border-b border-[#e4e1d3] pb-2">
            <h2 className="text-sm font-black text-[#174327] uppercase tracking-wider font-heading flex items-center gap-2">
              <Award className="w-4 h-4 text-[#1c5a35]" />
              <span>DEMONSTRATION GRADING</span>
            </h2>
            <span className="text-[10px] font-bold text-[#1c5a35] bg-[#e0eee2] border border-[#bcd6c0] px-2 py-0.5 rounded-full uppercase">
              Standard Calibration
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-5 rounded-2xl border-2 border-[#bcd6c0] bg-[#e0eee2]/50 flex items-center justify-between">
              <div>
                <span className="text-xs font-bold text-[#1c5a35] uppercase tracking-wider">{t.gradeA} Estimated</span>
                <div className="text-3xl font-black text-[#174327] font-heading mt-0.5">{record.gradeA}%</div>
                <p className="text-[11px] text-[#1c5a35] mt-1">Acceptable for official procurement intake</p>
              </div>
              <div className="text-xl font-black text-[#174327] px-3.5 py-1.5 bg-[#e0eee2] border border-[#bcd6c0] rounded-xl font-heading">
                GRADE A
              </div>
            </div>

            <div className="p-5 rounded-2xl border-2 border-[#e5c1ba] bg-[#f6e5e1]/50 flex items-center justify-between">
              <div>
                <span className="text-xs font-bold text-[#a93b2e] uppercase tracking-wider">{t.gradeURS} Estimated</span>
                <div className="text-3xl font-black text-[#a93b2e] font-heading mt-0.5">{record.gradeURS}%</div>
                <p className="text-[11px] text-[#a93b2e] mt-1">Under-size, Rotten & Sprouted deduction</p>
              </div>
              <div className="text-xl font-black text-[#a93b2e] px-3.5 py-1.5 bg-[#f6e5e1] border border-[#e5c1ba] rounded-xl font-heading">
                URS
              </div>
            </div>
          </div>
        </div>

        {/* SECTION 3: ASSESSMENT SUMMARY */}
        <div className="space-y-2 bg-[#f7f5ee] p-4.5 rounded-2xl border border-[#cfcbb8] text-xs">
          <h3 className="font-bold text-[#174327] uppercase tracking-wider font-heading">{t.assessmentSummary}</h3>
          <p className="text-[#1c2a20] leading-relaxed">
            "{record.qualitySummary}"
          </p>
          <p className="text-[#55665b] text-[11px] pt-1">
            Consignment load: {record.batch.approxQuantity} • Evaluated under uniform light calibration.
          </p>
        </div>

        {/* IMPORTANT NOTICE / DISCLAIMER */}
        <div className="p-4.5 bg-[#f6ecd4] border border-[#d9bf85] rounded-2xl text-xs text-[#4d3504] flex items-start gap-3">
          <Info className="w-5 h-5 text-[#8a5f12] shrink-0 mt-0.5" />
          <div className="space-y-1">
            <span className="font-bold text-[#4d3504] block uppercase tracking-wider text-[11px] font-heading">Important Notice</span>
            <p className="leading-relaxed text-[#55665b]">
              {record.isDemoData ? t.reportNotice : "This report is generated by an SIH prototype operating in Demo Mode. It is not an official quality certificate."}
            </p>
          </div>
        </div>

        {/* Signatures & Verification Stamp */}
        <div className="pt-6 border-t border-[#cfcbb8] grid grid-cols-2 gap-8 text-xs text-[#55665b]">
          <div className="space-y-4">
            <div className="font-mono text-[10px] text-[#55665b]">
              HASH: SHA256-DEMO-{record.reportId.replace(/-/g, '')}
            </div>
            <div className="pt-6 border-t border-[#cfcbb8]">
              <span className="font-bold text-[#1c2a20] block">Digitally Certified (Demo Mode)</span>
              <span>OnionGuard AI Automated Inspection System</span>
            </div>
          </div>

          <div className="space-y-4 text-right">
            <div className="font-mono text-[10px] text-[#55665b]">
              SIH26031 • Procurement Transparency
            </div>
            <div className="pt-6 border-t border-[#cfcbb8]">
              <span className="font-bold text-[#1c2a20] block">{record.batch.inspectorName}</span>
              <span>Procurement Center Verification Officer</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
